{{- if .Values.global.oxshibboleth.enabled }}

{{- /* Start of TraefikService definition */}}
{{- if eq .Values.gateway.className "traefik" }}
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: oxshibboleth-traefik
  namespace: {{ .Release.Namespace }}
spec:
  weighted:
    services:
    - name: oxshibboleth
      port: 8080
      sticky:
        cookie:
          name: "shib-stateful-route"
          path: "/idp"
          secure: true
          httpOnly: true
{{- end }}
{{- /* End of TraefikService definition */}}

{{- end }}
